--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2022-05-04 08:19:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3035 (class 1262 OID 51769)
-- Name: UkrposhtaDb; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "UkrposhtaDb" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Ukrainian_Ukraine.1251';


ALTER DATABASE "UkrposhtaDb" OWNER TO postgres;

\connect "UkrposhtaDb"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 51777)
-- Name: Department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Department" (
    "Id" integer NOT NULL,
    "Name" character varying(20) NOT NULL
);


ALTER TABLE public."Department" OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 51775)
-- Name: Department_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Department" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Department_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 51796)
-- Name: Employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Employee" (
    "Code" integer NOT NULL,
    "Name" text NOT NULL,
    "Surname" text NOT NULL,
    "Lastname" text NOT NULL,
    "Phone" text NOT NULL,
    "Address" text NOT NULL,
    "IdDepartment" integer NOT NULL,
    "IdPosition" integer NOT NULL,
    "Salary" numeric(10,2) NOT NULL,
    "IdPremium" integer NOT NULL
);


ALTER TABLE public."Employee" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 51784)
-- Name: Position; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Position" (
    "Id" integer NOT NULL,
    "Name" character varying(20) NOT NULL
);


ALTER TABLE public."Position" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 51782)
-- Name: Position_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Position" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Position_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 51791)
-- Name: Premium; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Premium" (
    "Id" integer NOT NULL,
    "Name" character varying(1) NOT NULL,
    "Value" numeric(3,0) NOT NULL
);


ALTER TABLE public."Premium" OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 51789)
-- Name: Premium_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Premium" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Premium_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 51770)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3024 (class 0 OID 51777)
-- Dependencies: 202
-- Data for Name: Department; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Department" ("Id", "Name") VALUES (1, 'Відділ кадрів');
INSERT INTO public."Department" ("Id", "Name") VALUES (2, 'Відділ страхування');


--
-- TOC entry 3029 (class 0 OID 51796)
-- Dependencies: 207
-- Data for Name: Employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Employee" ("Code", "Name", "Surname", "Lastname", "Phone", "Address", "IdDepartment", "IdPosition", "Salary", "IdPremium") VALUES (111111, 'Василь', 'Антонюк', 'Романович', '+38(123)456-78-90', 'Київ', 1, 1, 10000.00, 1);
INSERT INTO public."Employee" ("Code", "Name", "Surname", "Lastname", "Phone", "Address", "IdDepartment", "IdPosition", "Salary", "IdPremium") VALUES (111115, 'Анна', 'Герасимчук', 'Василівна', '+38(234)567-89-01', 'Львів', 2, 2, 8000.00, 3);


--
-- TOC entry 3026 (class 0 OID 51784)
-- Dependencies: 204
-- Data for Name: Position; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Position" ("Id", "Name") VALUES (1, 'Бухгалтер');
INSERT INTO public."Position" ("Id", "Name") VALUES (2, 'Менеджер');


--
-- TOC entry 3028 (class 0 OID 51791)
-- Dependencies: 206
-- Data for Name: Premium; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Premium" ("Id", "Name", "Value") VALUES (1, 'A', 20);
INSERT INTO public."Premium" ("Id", "Name", "Value") VALUES (2, 'B', 30);
INSERT INTO public."Premium" ("Id", "Name", "Value") VALUES (3, 'C', 40);


--
-- TOC entry 3022 (class 0 OID 51770)
-- Dependencies: 200
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20220503191352_InitDB', '6.0.4');


--
-- TOC entry 3036 (class 0 OID 0)
-- Dependencies: 201
-- Name: Department_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Department_Id_seq"', 2, true);


--
-- TOC entry 3037 (class 0 OID 0)
-- Dependencies: 203
-- Name: Position_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Position_Id_seq"', 2, true);


--
-- TOC entry 3038 (class 0 OID 0)
-- Dependencies: 205
-- Name: Premium_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Premium_Id_seq"', 3, true);


--
-- TOC entry 2875 (class 2606 OID 51781)
-- Name: Department PK_Department; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Department"
    ADD CONSTRAINT "PK_Department" PRIMARY KEY ("Id");


--
-- TOC entry 2888 (class 2606 OID 51803)
-- Name: Employee PK_Employee; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "PK_Employee" PRIMARY KEY ("Code");


--
-- TOC entry 2878 (class 2606 OID 51788)
-- Name: Position PK_Position; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Position"
    ADD CONSTRAINT "PK_Position" PRIMARY KEY ("Id");


--
-- TOC entry 2882 (class 2606 OID 51795)
-- Name: Premium PK_Premium; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Premium"
    ADD CONSTRAINT "PK_Premium" PRIMARY KEY ("Id");


--
-- TOC entry 2872 (class 2606 OID 51774)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2873 (class 1259 OID 51819)
-- Name: IX_Department_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Department_Name" ON public."Department" USING btree ("Name");


--
-- TOC entry 2883 (class 1259 OID 51820)
-- Name: IX_Employee_IdDepartment; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Employee_IdDepartment" ON public."Employee" USING btree ("IdDepartment");


--
-- TOC entry 2884 (class 1259 OID 51821)
-- Name: IX_Employee_IdPosition; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Employee_IdPosition" ON public."Employee" USING btree ("IdPosition");


--
-- TOC entry 2885 (class 1259 OID 51822)
-- Name: IX_Employee_IdPremium; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Employee_IdPremium" ON public."Employee" USING btree ("IdPremium");


--
-- TOC entry 2886 (class 1259 OID 51823)
-- Name: IX_Employee_Phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Employee_Phone" ON public."Employee" USING btree ("Phone");


--
-- TOC entry 2876 (class 1259 OID 51824)
-- Name: IX_Position_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Position_Name" ON public."Position" USING btree ("Name");


--
-- TOC entry 2879 (class 1259 OID 51825)
-- Name: IX_Premium_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Premium_Name" ON public."Premium" USING btree ("Name");


--
-- TOC entry 2880 (class 1259 OID 51826)
-- Name: IX_Premium_Value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Premium_Value" ON public."Premium" USING btree ("Value");


--
-- TOC entry 2889 (class 2606 OID 51804)
-- Name: Employee FK_Employee_Department_IdDepartment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "FK_Employee_Department_IdDepartment" FOREIGN KEY ("IdDepartment") REFERENCES public."Department"("Id") ON DELETE CASCADE;


--
-- TOC entry 2890 (class 2606 OID 51809)
-- Name: Employee FK_Employee_Position_IdPosition; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "FK_Employee_Position_IdPosition" FOREIGN KEY ("IdPosition") REFERENCES public."Position"("Id") ON DELETE CASCADE;


--
-- TOC entry 2891 (class 2606 OID 51814)
-- Name: Employee FK_Employee_Premium_IdPremium; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "FK_Employee_Premium_IdPremium" FOREIGN KEY ("IdPremium") REFERENCES public."Premium"("Id") ON DELETE CASCADE;


-- Completed on 2022-05-04 08:19:43

--
-- PostgreSQL database dump complete
--

